sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install pytest pytest-cov coveralls
script:
  - py.test -v --cov=date_guesser_rc test/
after_success:
  - coveralls
